version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/path_to_your_google_service_account.json
      - EMAIL_ADDRESS=your_email@example.com
      - EMAIL_PASSWORD=your_email_password

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
